import type { Metadata } from "next";
import "./styles/globals.css";
import { Providers } from "./provider";
import { LoadingProvider } from "./context/LoadingContext";
import LoadingOverlay from "./context/LoadingOverlay";
import EditorAuthWrapper from "./EditorAuthWrapper";
import MockEditorAuthWrapper from "./fakers/MockEditorAuthWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white text-black dark:bg-black dark:text-white">
        <Providers>
          <LoadingProvider>
            <MockEditorAuthWrapper>
              {/* <EditorAuthWrapper> */}
                <LoadingOverlay />
                {children}
              {/* </EditorAuthWrapper> */}
            </MockEditorAuthWrapper>
          </LoadingProvider>
        </Providers>
      </body>
    </html>
  );
}
